# Default connection url: postgres://postgres:DQhHLe4Z!p45FZYgTyXk@localhost:5432/postgres

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: DQhHLe4Z!p45FZYgTyXk
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:6.2.5
    command: redis-server --requirepass DQhHLe4Z
    ports:
      - 6379:6379
volumes:
  data: ~
